---
title: "Overview"
type: docs
menu:
  main:
    name: "Overview"
    identifier: "tutorials-get-started"
    parent: "tutorials-top"
    weight: 10
aliases:
  - /tensorflow/articles/tutorial_mnist_beginners.html
  - /tensorflow/articles/tutorial_mnist_pros.html
  - /tensorflow/articles/tutorial_tensorflow_mechanics.html
---

In this section you will find tutorials that can be used to get started with TensorFlow for R or, for more advanced users, to discover best practices for loading data, building complex models and solving common problems.

The best place to get started with TensorFlow is using Keras - a Deep Learning API
created by François Chollet and ported to R by JJ Allaire. Keras makes it easy to get started, and it allows you to progressively 
build more complex workflows as you need to use advanced models and techniques. 

## For beginners

We recommend the following tutorials for your first contact with TensorFlow. 
Feel free to navigate through the 'beginners' section in the sidebar.

- [Quickstart](/tutorials/beginners/): the minimal getting started guide to Keras.
- [Basic ML with Keras](/tutorials/beginners/basic-ml/): use Keras to solve basic Machine Learning tasks.
- [Load data](/tutorials/beginners/load/load_csv/): learn to efficiently load data to TensorFlow using `tfdatasets`.

## For experts

- [Advanced Quickstart](/tutorials/advanced/): learn the subclassing API and how to create custom loops.
- [Customization](/tutorials/advanced/customization/tensors-operations/): build custom layers and training loops in TensorFlow.
- [Distributed Training](/tutorials/advanced/distributed/distributed_training_with_keras/): distribute your model training across multiple GPU's or machines.


We also provide tutorials focused on different types of data:

- [Images](/tutorials/advanced/images/cnn/): Build more advanced models for classification and segmentation of images.
- [Structured Data](/tutorials/advanced/structured/classify/): Build models
for structured data.
