---
execute:
  freeze: true
---

[R/dataset_methods.R](https://github.com/rstudio/tfdatasets//blob/main/R/dataset_methods.R#L262) 

# dataset_concatenate

## Creates a dataset by concatenating given dataset with this dataset.

## Description
 Creates a dataset by concatenating given dataset with this dataset. 


## Usage
```r
 
dataset_concatenate(dataset, ...) 
```

## Arguments
|Arguments|Description|
|---|---|
| dataset, ... | `tf_dataset`s to be concatenated |



## Value
 A dataset 

## Note
 Input dataset and dataset to be concatenated should have same nested structures and output types. 


## See Also
 Other dataset methods:  `dataset_batch()`, `dataset_cache()`, `dataset_collect()`, `dataset_decode_delim()`, `dataset_filter()`, `dataset_interleave()`, `dataset_map_and_batch()`, `dataset_map()`, `dataset_padded_batch()`, `dataset_prefetch_to_device()`, `dataset_prefetch()`, `dataset_reduce()`, `dataset_repeat()`, `dataset_shuffle_and_repeat()`, `dataset_shuffle()`, `dataset_skip()`, `dataset_take_while()`, `dataset_take()`, `dataset_window()` 

