---
execute:
  freeze: true
---

[R/data.R](https://github.com/rstudio/tfdatasets//blob/main/R/data.R#L) 

# hearts

## Heart Disease Data Set

## Description
 Heart disease (angiographic disease status) dataset. 

## Format

 A data frame with 303 rows and 14 variables:  

age

age in years

 

sex

sex (1 = male; 0 = female)

 

cp

chest pain type: Value 1: typical angina, Value 2: atypical angina, 

 

trestbps

resting blood pressure (in mm Hg on admission to the hospital)

 

chol

 serum cholestoral in mg/dl 

 

fbs

(fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)

 

restecg

resting electrocardiographic results: Value 0: normal, Value 1: 

 

thalach

maximum heart rate achieved

 

exang

exercise induced angina (1 = yes; 0 = no)

 

oldpeak

ST depression induced by exercise relative to rest

 

slope

the slope of the peak exercise ST segment: Value 1: upsloping, 

 

ca

number of major vessels (0-3) colored by flourosopy

 

thal

3 = normal; 6 = fixed defect; 7 = reversable defect

 

target

diagnosis of heart disease angiographic

  

## Usage
```r
 
hearts 
```








