---
execute:
  freeze: true
---

[R/initializers.R](https://github.com/rstudio/keras//blob/main/R/initializers.R#L83) 

# initializer_truncated_normal

## Initializer that generates a truncated normal distribution.

## Description
 These values are similar to values from an `initializer_random_normal()` except that values more than two standard deviations from the mean are discarded and re-drawn. This is the recommended initializer for neural network weights and filters. 


## Usage
```r
 
initializer_truncated_normal(mean = 0, stddev = 0.05, seed = NULL) 
```

## Arguments
|Arguments|Description|
|---|---|
| mean | Mean of the random values to generate. |
| stddev | Standard deviation of the random values to generate. |
| seed | Integer used to seed the random generator. |






## See Also
 Other initializers:  `initializer_constant()`, `initializer_glorot_normal()`, `initializer_glorot_uniform()`, `initializer_he_normal()`, `initializer_he_uniform()`, `initializer_identity()`, `initializer_lecun_normal()`, `initializer_lecun_uniform()`, `initializer_ones()`, `initializer_orthogonal()`, `initializer_random_normal()`, `initializer_random_uniform()`, `initializer_variance_scaling()`, `initializer_zeros()` 

