---
execute:
  freeze: true
---

[R/backend.R](https://github.com/rstudio/keras//blob/main/R/backend.R#L1727) 

# k_mean

## Mean of a tensor, alongside the specified axis.

## Description
 Mean of a tensor, alongside the specified axis. 


## Usage
```r
 
k_mean(x, axis = NULL, keepdims = FALSE) 
```

## Arguments
|Arguments|Description|
|---|---|
| x | A tensor or variable. |
| axis | A list of axes to compute the mean over (axis indexes are 1-based). |
| keepdims | A boolean, whether to keep the dimensions or not. If `keepdims` is `FALSE`, the rank of the tensor is reduced by 1 for each entry in `axis`. If `keep_dims` is `TRUE`, the reduced dimensions are retained with length 1. |


## Section

## Keras Backend

   This function is part of a set of Keras backend functions that enable lower level access to the core operations of the backend tensor engine (e.g. TensorFlow, CNTK, Theano, etc.).  You can see a list of all available backend functions here: [https://keras.rstudio.com/articles/backend.html#backend-functions](https://keras.rstudio.com/articles/backend.html#backend-functions). 

## Value
 A tensor with the mean of elements of `x`. 




