---
execute:
  freeze: true
---

[R/backend.R](https://github.com/rstudio/keras//blob/main/R/backend.R#L1827) 

# k_normalize_batch_in_training

## Computes mean and std for batch then apply batch_normalization on batch.

## Description
 Computes mean and std for batch then apply batch_normalization on batch. 


## Usage
```r
 
k_normalize_batch_in_training(x, gamma, beta, reduction_axes, epsilon = 0.001) 
```

## Arguments
|Arguments|Description|
|---|---|
| x | Input tensor or variable. |
| gamma | Tensor by which to scale the input. |
| beta | Tensor with which to center the input. |
| reduction_axes | iterable of integers, axes over which to normalize. |
| epsilon | Fuzz factor. |


## Section

## Keras Backend

   This function is part of a set of Keras backend functions that enable lower level access to the core operations of the backend tensor engine (e.g. TensorFlow, CNTK, Theano, etc.).  You can see a list of all available backend functions here: [https://keras.rstudio.com/articles/backend.html#backend-functions](https://keras.rstudio.com/articles/backend.html#backend-functions). 

## Value
 A list length of 3, `(normalized_tensor, mean, variance)`. 




