---
execute:
  freeze: true
---

[R/backend.R](https://github.com/rstudio/keras//blob/main/R/backend.R#L2096) 

# k_random_binomial

## Returns a tensor with random binomial distribution of values.

## Description
 `k_random_binomial()` and `k_random_bernoulli()` are aliases for the same function. Both are maintained for backwards compatibility. New code should prefer `k_random_bernoulli()`. 


## Usage
```r
 
k_random_binomial(shape, p = 0, dtype = NULL, seed = NULL) 
 
k_random_bernoulli(shape, p = 0, dtype = NULL, seed = NULL) 
```

## Arguments
|Arguments|Description|
|---|---|
| shape | A list of integers, the shape of tensor to create. |
| p | A float, `0. <= p <= 1`, probability of binomial distribution. |
| dtype | String, dtype of returned tensor. |
| seed | Integer, random seed. |


## Section

## Keras Backend

   This function is part of a set of Keras backend functions that enable lower level access to the core operations of the backend tensor engine (e.g. TensorFlow, CNTK, Theano, etc.).  You can see a list of all available backend functions here: [https://keras.rstudio.com/articles/backend.html#backend-functions](https://keras.rstudio.com/articles/backend.html#backend-functions). 

## Value
 A tensor. 




